name = "workflow_dispatch-worker-with-cron-trigger"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-05"

[vars]
GITHUB_OWNER = ""
GITHUB_REPO = ""
GITHUB_WORKFLOW_FILE_NAME = ""
GITHUB_BRANCH = ""

[triggers]
crons = ["* * * * *"]
# crons = []
